name: thyra_bridge_dart
description: A dart package bridge to libthyra native library.
version: 0.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
   path: ^1.8.0
   ffi: ^2.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0